// src/pages/HomePage.svelte
<script lang="ts" context="module">
    import type { DropdownOption } from "~/components/Dropdown.svelte";

    const lengthOptions: DropdownOption<number>[] = [
        { name: "Shortest", value: 0.2 },
        { name: "Shorter", value: 0.3 },
        { name: "Short", value: 0.4 },
        { name: "Medium", value: 0.5 },
        { name: "Long", value: 0.6 },
        { name: "Longer", value: 0.7 },
        { name: "Longest", value: 0.8 },
    ] as const;

    const transOptions: DropdownOption<number>[] = [
        { name: "3 Speed", value: 3 },
        { name: "4 Speed", value: 4 },
        { name: "5 Speed", value: 5 },
        { name: "6 Speed", value: 6 },
        { name: "7 Speed", value: 7 },
        { name: "8 Speed", value: 8 },
        { name: "9 Speed", value: 9 },
        { name: "10 Speed", value: 10 },
    ] as const;
</script>

<script lang="ts">
    import Dropdown from "~/components/Dropdown.svelte";
    import GearInput, { isGearValid } from "~/components/GearInput.svelte";
    import { tuneGearing } from "~/libs/tuner";

    let launchGearInput: GearInput;
    let finalGearInput: GearInput;

    let length = $state(lengthOptions[3].value);
    let trans = $state(transOptions[3].value);
    let launchGear = $state(NaN);
    let finalGear = $state(NaN);
    let calculation = $state<number[]>();

    const handleClick = (launchGearPos: number) => {
        const launchGearValidation = launchGearInput.validate();
        const finalGearValidation = finalGearInput.validate();
        if (!launchGearValidation || !finalGearValidation) {
            return;
        }

        const minFactor = (finalGear / launchGear) ** (1 / (trans - 1));
        const lengthFactor = Math.expLerp(minFactor, 1 / minFactor, length);
        calculation = tuneGearing(lengthFactor, trans, launchGearPos, launchGear, finalGear);
    };
</script>

<main class="container">
    <hgroup>
        <h1>Forza #1 Gearing Tuner</h1>
        <h1>The best gearing tuner for the Forza series</h1>
    </hgroup>

    <div class="grid">
        <Dropdown label="Length" options={lengthOptions} bind:value={length} />
        <Dropdown label="Transmission" options={transOptions} bind:value={trans} />

        <GearInput
            label="Launch Gear"
            placeholder="2.89"
            bind:value={launchGear}
            bind:this={launchGearInput}
        />

        <GearInput
            label="Final Gear"
            placeholder="0.78"
            bind:value={finalGear}
            bind:this={finalGearInput}
        />
    </div>

    <div class="grid">
        <button onclick={() => handleClick(2)} class="secondary">Tune second gear launch</button>
        <button onclick={() => handleClick(1)}>Tune first gear launch</button>
    </div>
    <p />

    {#if calculation}
        <article>
            {#each calculation as gear, i}
                {#if i !== 0}
                    <hr />
                {/if}
                <nav>
                    <div>Gear {i + 1}</div>
                    {#if isGearValid(gear)}
                        <div>{gear.toFixed(2)}</div>
                    {:else}
                        <div>Failed</div>
                    {/if}
                </nav>
            {/each}
        </article>
    {/if}
</main>

// src/pages/HomePage.tsx
import { Index, Show } from "solid-js";
import { tuneGearing } from "~/libs/tuner";
import { createSignal } from "~/libs/primitive";
import GearInput, { GearInputRef, isGearValid } from "~/components/GearInput";
import Dropdown, { DropdownOption } from "~/components/Dropdown";

const LengthOptions: DropdownOption<number>[] = [
    { name: "Shortest", value: 0.2 },
    { name: "Shorter", value: 0.3 },
    { name: "Short", value: 0.4 },
    { name: "Medium", value: 0.5 },
    { name: "Long", value: 0.6 },
    { name: "Longer", value: 0.7 },
    { name: "Longest", value: 0.8 },
] as const;

const TransOptions: DropdownOption<number>[] = [
    { name: "3 Speed", value: 3 },
    { name: "4 Speed", value: 4 },
    { name: "5 Speed", value: 5 },
    { name: "6 Speed", value: 6 },
    { name: "7 Speed", value: 7 },
    { name: "8 Speed", value: 8 },
    { name: "9 Speed", value: 9 },
    { name: "10 Speed", value: 10 },
] as const;

export default () => {
    let launchGearInput: GearInputRef;
    let finalGearInput: GearInputRef;

    const length = createSignal(LengthOptions[3].value);
    const trans = createSignal(TransOptions[3].value);
    const launchGear = createSignal(NaN);
    const finalGear = createSignal(NaN);
    const calculation = createSignal([] as number[]);

    const handleClick = (launchGearPos: number) => {
        const launchGearValidation = launchGearInput.validate();
        const finalGearValidation = finalGearInput.validate();
        if (!launchGearValidation || !finalGearValidation) {
            return;
        }

        const minFactor = (finalGear.get() / launchGear.get()) ** (1 / (trans.get() - 1));
        const lengthFactor = Math.expLerp(minFactor, 1 / minFactor, length.get());
        calculation.set(
            tuneGearing(lengthFactor, trans.get(), launchGearPos, launchGear.get(), finalGear.get())
        );
    };

    return (
        <main class="container">
            <div class="headings">
                <h1>F1 Gearing Tuner</h1>
                <h1>The best gearing tuner for the Forza series</h1>
            </div>

            <div class="grid">
                <Dropdown
                    label="Length"
                    options={LengthOptions}
                    value={length.get()}
                    onChange={length.set}
                />

                <Dropdown
                    label="Transmission"
                    options={TransOptions}
                    value={trans.get()}
                    onChange={trans.set}
                />

                <GearInput
                    label="Launch Gear"
                    onChange={launchGear.set}
                    ref={(ref) => (launchGearInput = ref)}
                />

                <GearInput
                    label="Final Gear"
                    onChange={finalGear.set}
                    ref={(ref) => (finalGearInput = ref)}
                />
            </div>

            <div class="grid">
                <button onClick={() => handleClick(1)}>Tune first gear launch</button>
                <button onClick={() => handleClick(2)}>Tune second gear launch</button>
            </div>

            <Index each={calculation.get()}>
                {(gear, i) => (
                    <>
                        <Show when={i !== 0}>
                            <hr />
                        </Show>
                        <nav>
                            <div>Gear {i + 1}</div>
                            <Show when={isGearValid(gear())} fallback="Failed">
                                {gear().toFixed(2)}
                            </Show>
                        </nav>
                    </>
                )}
            </Index>
        </main>
    );
};
