// src/app/Layout.tsx
import { JSX } from "solid-js/jsx-runtime";

type Props = {
    version: string;
    url: string;
    children?: JSX.Element;
};

export default (props: Props) => {
    return (
        <>
            <nav class="container-fluid">
                <ul />
                <ul>
                    <li>Version {props.version}</li>
                    <li>•</li>
                    <li>
                        <a href={props.url}>Source Code</a>
                    </li>
                </ul>
            </nav>
            {props.children}
        </>
    );
};

// src/pages/Layout.svelte
<script lang="ts">
    import type { Children } from "~/libs/children";

    type LayoutProps = {
        url: string;
        children?: Children;
    };

    const { url, children }: LayoutProps = $props();
</script>

<nav class="container-fluid">
    <ul />
    <ul>
        <li>
            <a href={url}>Source Code</a>
        </li>
    </ul>
</nav>

{#if children}
    {@render children()}
{/if}
