// src/libs/GearInput.svelte
<script lang="ts" context="module">
    export type GearInputProps = {
        label: string;
        placeholder?: string;
        value?: number;
    };

    export function isGearValid(gear: number) {
        return 0.48 <= gear && gear <= 6;
    }
</script>

<script lang="ts">
    import { gearInput as intl } from "@libs/intl";

    // eslint-disable-next-line @typescript-eslint/no-unused-vars
    let { label, placeholder, value = $bindable(NaN) }: GearInputProps = $props();

    let input = $state("");
    let message = $state("");
    let valid = $state(true);

    export function validate(): boolean {
        const formattedInput = input.replaceAll(",", ".").trim();
        if (formattedInput === "") {
            return whenInvalid(intl.emptyError);
        }

        const gear = Number(formattedInput);
        if (isNaN(gear)) {
            return whenInvalid(intl.typeError);
        }

        if (!isGearValid(gear)) {
            return whenInvalid(intl.rangeError("0.48", "6.00"));
        }

        return whenValid(gear);
    }

    function whenValid(gear: number): boolean {
        const fixedGear = gear.toFixed(2);
        value = Number(fixedGear);
        input = fixedGear;
        message = "";
        valid = true;
        return true;
    }

    function whenInvalid(cause: string): boolean {
        value = NaN;
        message = cause;
        valid = false;
        return false;
    }
</script>

<label>
    {label}
    <input
        {placeholder}
        inputmode="decimal"
        onchange={validate}
        aria-invalid={valid ? undefined : true}
        bind:value={input}
    />
    <small>{message}</small>
</label>

// src/components/GearInput.tsx
import { JSX, onMount } from "solid-js";
import { createSignal } from "~/libs/primitive";

const Config = {
    min: 0.48,
    max: 6,
} as const;

export type GearInputRef = {
    validate: () => boolean;
};

export type GearInputProps = {
    label: string;
    onChange?: (value: number) => void;
    ref?: (ref: GearInputRef) => void;
};

export const isGearValid = (gear: number) => {
    return Config.min <= gear && gear <= Config.max;
};

export default (props: GearInputProps) => {
    const input = createSignal("");
    const valid = createSignal(true);
    const placeholder = `${Config.min.toFixed(2)}-${Config.max.toFixed(2)}`;

    const whenValid = (gear: number) => {
        const formatted = gear.toFixed(2);
        props.onChange?.(Number(formatted));
        input.set(formatted);
        valid.set(true);
        return true;
    };

    const whenInvalid = () => {
        props.onChange?.(NaN);
        valid.set(false);
        return false;
    };

    const validate = () => {
        const trimmed = input.get().trim();
        if (trimmed === "") {
            return whenInvalid();
        }

        const gear = Number(trimmed.replaceAll(",", "."));
        return isGearValid(gear) ? whenValid(gear) : whenInvalid();
    };

    const handleChange: JSX.EventHandler<HTMLInputElement, Event> = (e) => {
        input.set(e.currentTarget.value);
        validate();
    };

    onMount(() => props.ref?.({ validate }));

    return (
        <label>
            {props.label}
            <input
                inputmode="decimal"
                value={input.get()}
                placeholder={placeholder}
                onChange={handleChange}
                aria-invalid={valid.get() ? undefined : true}
            />
        </label>
    );
};
