// src/libs/components/Dropdown.svelte
<script lang="ts" module>
    import type { ChangeEventHandler } from "svelte/elements";

    export type DropdownOption = {
        name: string;
        value: number;
    };

    type Props = {
        label: string;
        options: DropdownOption[];
        value?: number;
    };
</script>

<script lang="ts">
    let { label, options, value = $bindable(options[0].value) }: Props = $props();

    const eventHandler: ChangeEventHandler<HTMLSelectElement> = (e) => {
        const index = e.currentTarget.selectedIndex;
        value = options[index].value;
    };
</script>

<label>
    {label}

    <select {value} onchange={eventHandler}>
        {#each options as { name, value }}
            <option {value}>{name}</option>
        {/each}
    </select>
</label>

// src/component/Dropdown.tsx
import { For, JSX } from "solid-js";

type Props<T extends DropdownValue> = {
    label: string;
    options: DropdownOption<T>[];
    value?: T;
    onChange?: (value: T) => void;
};

export type DropdownValue = string | number | string[] | undefined;
export type DropdownOption<T extends DropdownValue> = { name: string; value: T };

export default <T extends DropdownValue>({ label, options, value, onChange }: Props<T>) => {
    const handleChange: JSX.EventHandler<HTMLSelectElement, Event> = (e) => {
        const index = e.currentTarget.selectedIndex;
        if (0 <= index && index < options.length) {
            onChange?.(options[index].value);
        }
    };

    return (
        <label>
            {label}
            <select value={value ?? options[0].value} onChange={handleChange}>
                <For each={options}>
                    {(option) => <option value={option.value}>{option.name}</option>}
                </For>
            </select>
        </label>
    );
};
