// src/components/GearInput.svelte
<script lang="ts" context="module">
    const MIN = 0.48;
    const MAX = 6;
    const placeholder = `${MIN.toFixed(2)}-${MAX.toFixed(2)}`;

    export const isGearValid = (gear: number) => {
        return MIN <= gear && gear <= MAX;
    };

    export type GearInputRef = {
        validate: () => boolean;
    };

    export type GearInputProps = {
        label: string;
        onChange?: (value: number) => void;
    };
</script>

<script lang="ts">
    const { label, onChange }: GearInputProps = $props();

    let input = $state("");
    let valid = $state(true);

    const whenValid = (gear: number) => {
        const formatted = gear.toFixed(2);
        onChange?.(Number(formatted));
        input = formatted;
        valid = true;
        return true;
    };

    const whenInvalid = () => {
        onChange?.(NaN);
        valid = false;
        return false;
    };

    export const validate = () => {
        const trimmed = input.trim();
        if (trimmed === "") {
            return whenInvalid();
        }

        const gear = Number(trimmed.replaceAll(",", "."));
        return isGearValid(gear) ? whenValid(gear) : whenInvalid();
    };
</script>

<label>
    <div>{label}</div>
    <input
        bind:value={input}
        {placeholder}
        inputmode="decimal"
        onchange={validate}
        aria-invalid={valid ? undefined : true}
    />
</label>

// src/component/GearInput.tsx
import { JSX, onCleanup, onMount } from "solid-js";
import { Delegate } from "~/lib/delegate";
import { createState } from "~/lib/primitive";

type Props = {
    label: string;
    onChange?: (value: number) => void;
    validation?: Delegate;
};

export default (props: Props) => {
    const input = createState({
        value: "",
        valid: true,
    });

    const handleChange: JSX.EventHandler<HTMLInputElement, Event> = (e) => {
        input.value = e.currentTarget.value;
        validate();
    };

    const validate = () => {
        const gearRatio = Number(input.value);

        if (0.48 <= gearRatio && gearRatio <= 6.0) {
            const formatted = gearRatio.toFixed(2);
            props.onChange?.(Number(formatted));
            input.value = formatted;
            input.valid = true;
        } else {
            props.onChange?.(NaN);
            input.valid = false;
        }
    };

    onMount(() => props.validation?.add(validate));
    onCleanup(() => props.validation?.remove(validate));

    return (
        <label>
            {props.label}
            <input
                placeholder="0.48-6.00"
                inputmode="numeric"
                value={input.value}
                onChange={handleChange}
                aria-invalid={input.valid ? undefined : true}
            />
        </label>
    );
};
